package chapter02.jdbc;

import chapter02.hibernate.Message;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import static org.testng.Assert.assertEquals;

public class PersistenceTest {
    @BeforeSuite
    public void setup() {
        try (Connection connection = DriverManager.getConnection("jdbc:h2:./db2", "sa", "")) {
            // clear out the old data, if any, so we know the state of the DB
            try (PreparedStatement ps = connection.prepareStatement("DROP TABLE messages IF EXISTS")) {
                ps.execute();
            }
            try (PreparedStatement ps = connection.prepareStatement(
                    "CREATE TABLE messages ("
                            + "id BIGINT GENERATED BY DEFAULT AS IDENTITY "
                            + "PRIMARY KEY, "
                            + "text VARCHAR(256))"
            )) {
                ps.execute();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }

    @Test
    public void saveMessage() {
        try (Connection connection = DriverManager.getConnection("jdbc:h2:./db2", "sa", "")) {
            connection.setAutoCommit(false);
            try (PreparedStatement ps = connection.prepareStatement("INSERT INTO messages(text) VALUES (?)")) {
                ps.setString(1, "Hello, World");
                ps.execute();
                connection.commit();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }

    @Test(dependsOnMethods = "saveMessage")
    public void readMessage() {
        List<Message> list = new ArrayList<>();
        try (Connection connection = DriverManager.getConnection("jdbc:h2:./db2", "sa", "")) {
            try (PreparedStatement ps = connection.prepareStatement("SELECT id, text FROM messages")) {
                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        Message message = new Message();
                        message.setId(rs.getLong(1));
                        message.setText(rs.getString(2));
                        list.add(message);
                    }
                    assertEquals(list.size(), 1);
                    for (Message m : list) {
                        System.out.println(m);
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }
}